// 翻訳辞書
// 形式: 行番号: {ja: "日本語", en: "英語"}

const 辞書 = {
  100:   {ja: "次へ", en: "Next"},

  20100: {ja: "主訴確認", en: "Check your main reason for visit"},
  20200: {ja: "今回もっとも困っている症状は何ですか", en: "What symptom is bothering you the most today?"},
  20300: {ja: "痛み（頭痛、胸痛、腹痛、腰痛、関節痛、その他のからだの場所の痛み）", en: "Pain (such as headache, chest pain, stomach pain, back pain, joint pain, or pain in another part of the body)"},
  20400: {ja: "発熱", en: "Fever"},
  20500: {ja: "浮腫（顔、四肢などのむくみ）", en: "Swelling (for example, in the face or arms and legs)"},
  20600: {ja: "皮膚の異常", en: "Skin problems"},
  20700: {ja: "めまい（視野が動いて目が回る、足がふらふらする、体がフアフアする、気を失いそうになる）", en: "Dizziness (for example, feeling that the room is spinning, feeling unsteady, feeling light-headed, or feeling like you might faint)"},
  20800: {ja: "気を失った、気が遠くなった", en: "Fainted or felt like you were going to faint"},
  20900: {ja: "息が苦しい", en: "Shortness of breath"},
  21000: {ja: "咳や痰が出る", en: "Cough or phlegm"},
  21100: {ja: "吐き気や嘔吐、食欲不振がある", en: "Nausea, vomiting, or loss of appetite"},
  21200: {ja: "手足がしびれる", en: "Numbness in your hands or feet"},
  21300: {ja: "ここに上げられている症状のリストにない、これら以外の症状", en: "Other symptoms not listed here"},
  21400: {ja: "次へ", en: "Next"},

  22100: {ja: "最もつらい症状", en: "The most troubling symptom"},
  22200: {ja: "複数の症状があります。", en: "You have more than one symptom."},
  22300: {ja: "この中で最もつらい症状を選んでください。", en: "Please choose the symptom that is bothering you the most."},
  22400: {ja: "次へ", en: "Next"},

  30100: {ja: "痛みの部位", en: "Where the pain is"},
  30200: {ja: "どこが痛いのですか（複数選択可）", en: "Where does it hurt? (You can choose more than one.)"},
  30300: {ja: "頭", en: "Head"},
  30400: {ja: "のど", en: "Throat"},
  30500: {ja: "首", en: "Neck"},
  30600: {ja: "肩", en: "Shoulder"},
  30700: {ja: "胸（前胸部、乳房）", en: "Chest (front of the chest, breast)"},
  30800: {ja: "腹部", en: "Belly"},
  30900: {ja: "背部", en: "Back"},
  31000: {ja: "腰", en: "Lower back"},
  31100: {ja: "上肢（指、手首、肘）", en: "Arm or hand (fingers, wrist, elbow)"},
  31200: {ja: "下肢（足の指、足首、膝、足の付け根）", en: "Leg or foot (toes, ankle, knee, groin)"},
  31300: {ja: "その他", en: "Other"},
  31400: {ja: "次へ", en: "Next"},

  40100: {ja: "最も痛い部位", en: "The most painful area"},
  40200: {ja: "複数の部位に痛みがあります。", en: "You have pain in more than one place."},
  40300: {ja: "この中で最も痛い部位を選んでください。", en: "Please choose the most painful area."},
  40400: {ja: "次へ", en: "Next"},

  50100: {ja: "痛みの経過", en: "When the pain started"},
  50200: {ja: "首が、初めて痛いと感じたのは、いつ頃からですか", en: "When did you first notice pain in your neck?"},
  50300: {ja: "数時間前から", en: "A few hours ago"},
  50400: {ja: "24時間以内", en: "Within the last 24 hours"},
  50500: {ja: "1日～数日前から", en: "One to several days ago"},
  50600: {ja: "1週間くらい前から", en: "About a week ago"},
  50700: {ja: "数週間前から", en: "Several weeks ago"},
  50800: {ja: "1か月くらい前から", en: "About a month ago"},
  50900: {ja: "数か月前から", en: "Several months ago"},
  51000: {ja: "半年以上前から", en: "More than six months ago"},
  51100: {ja: "わからない", en: "I don't know"},
  51200: {ja: "次へ", en: "Next"},

  60100: {ja: "最初の痛みの持続時間", en: "How long the first pain lasted"},
  60200: {ja: "最初に痛みを感じた時の話を聞かせてください", en: "Please tell us about the first time you felt the pain."},
  60300: {ja: "その時の痛みはどのくらい続きましたか", en: "How long did that pain last?"},
  60400: {ja: "1分以内", en: "Less than 1 minute"},
  60500: {ja: "10分以内", en: "Less than 10 minutes"},
  60600: {ja: "1時間以内", en: "Less than 1 hour"},
  60700: {ja: "24時間以内", en: "Less than 24 hours"},
  60800: {ja: "1週間以内", en: "Less than 1 week"},
  60900: {ja: "1週間以上", en: "More than 1 week"},
  61000: {ja: "わからない", en: "I don't know"},
  61100: {ja: "次へ", en: "Next"},

  70100: {ja: "痛みの変化", en: "How the pain has changed"},
  70200: {ja: "最初に痛みを感じてから今日までの経過を教えてください", en: "Please tell us how the pain has changed since it first started until today."},
  70300: {ja: "痛みはどのように変化しましたか", en: "How has the pain changed?"},
  70400: {ja: "ずっと同じように痛い", en: "It has stayed about the same"},
  70500: {ja: "だんだん強くなっている", en: "It has been getting worse"},
  70600: {ja: "だんだん弱くなっている", en: "It has been getting better"},
  70700: {ja: "波のように強くなったり弱くなったりしている", en: "It comes and goes, getting worse and better like waves"},
  70800: {ja: "次へ", en: "Next"},

  80100: {ja: "痛みと姿勢・動作", en: "Pain and body position or movement"},
  80200: {ja: "痛みがひどくなる姿勢や動作はありますか", en: "Are there any positions or movements that make the pain worse?"},
  80300: {ja: "はい", en: "Yes"},
  80400: {ja: "いいえ", en: "No"},
  80500: {ja: "わからない", en: "I don't know"},
  80600: {ja: "逆に、痛みが楽になる姿勢や動作はありますか", en: "On the other hand, are there any positions or movements that make the pain better?"},
  80700: {ja: "はい", en: "Yes"},
  80800: {ja: "いいえ", en: "No"},
  80900: {ja: "わからない", en: "I don't know"},
  81000: {ja: "「はい」を選んだ場合は、あとで医師に詳しく伝えてください。", en: "If you choose \"Yes,\" please tell the doctor about it in detail later."},
  81100: {ja: "次へ", en: "Next"},

  90100: {ja: "既往の痛みの有無", en: "Past history of similar pain"},
  90200: {ja: "今回の痛みについてお聞きします", en: "We would like to ask about this pain."},
  90300: {ja: "痛みの強さは違っていても、以前に似たような痛みがありましたか", en: "Have you had similar pain before, even if it was not as strong?"},
  90400: {ja: "それとも人生で初めての痛みですか", en: "Or is this the first time in your life you have had this kind of pain?"},
  90500: {ja: "人生で初めての痛み", en: "First time ever"},
  90600: {ja: "前にも似たような痛みがあった", en: "I have had similar pain before"},
  90700: {ja: "わからない", en: "I don't know"},
  90800: {ja: "次へ", en: "Next"},

  100100: {ja: "その他の確認事項", en: "Other questions"},
  100200: {ja: "主な症状以外についてお聞きします", en: "We will also ask about things other than your main symptom."},
  100300: {ja: "食欲はありますか", en: "Do you have an appetite?"},
  100400: {ja: "変わりない", en: "No change"},
  100500: {ja: "落ちた", en: "Decreased"},
  100600: {ja: "実際の食事量はどうですか", en: "How much are you actually eating?"},
  100700: {ja: "いつもと変わらない", en: "About the same as usual"},
  100800: {ja: "いつもより少しだけ減った", en: "A little less than usual"},
  100900: {ja: "いつもの半分くらい", en: "About half of usual"},
  101000: {ja: "ほとんど食べられない", en: "Can hardly eat anything"},
  101100: {ja: "水分のみしか摂っていない", en: "Only drinking fluids"},
  101200: {ja: "次へ", en: "Next"},

  110100: {ja: "便通と睡眠", en: "Bowel movements and sleep"},
  110200: {ja: "便通（大便の出かた）に変化はありますか", en: "Has there been any change in your bowel movements?"},
  110300: {ja: "いつもと違う便通（下痢、または、便秘）", en: "Bowel movements are different from usual (diarrhea or constipation)"},
  110400: {ja: "いつもと同じ便通", en: "Bowel movements are the same as usual"},
  110500: {ja: "睡眠に変化はありますか", en: "Has there been any change in your sleep?"},
  110600: {ja: "いつも通りには眠れない", en: "I can't sleep as usual"},
  110700: {ja: "睡眠はいつも通り", en: "Sleep is the same as usual"},
  110800: {ja: "詳しい内容は、あとで医師が確認します。", en: "The doctor will check the details later."},
  110900: {ja: "次へ", en: "Next"},

  120100: {ja: "その他の健康情報", en: "Other health information"},
  120200: {ja: "おしっこが出にくいですか", en: "Is it hard to urinate?"},
  120300: {ja: "おしっこが出にくい", en: "Difficulty urinating"},
  120400: {ja: "おしっこの出はいつも通り", en: "Urination is the same as usual"},
  120500: {ja: "おしっこが出るとき痛いですか", en: "Does it hurt when you urinate?"},
  120600: {ja: "おしっこが出るとき、痛みがある", en: "Pain when urinating"},
  120700: {ja: "痛みはない", en: "No pain"},
  120800: {ja: "最近、自分のいるところがどこなのかわからなくなったことはありますか", en: "Have you recently been confused about where you are?"},
  120900: {ja: "わからなくなったことがある", en: "Yes, I have"},
  121000: {ja: "わからなくなったことはない", en: "No, I have not"},
  121100: {ja: "最近、気を失ったことはありますか", en: "Have you fainted recently?"},
  121200: {ja: "気を失ったことがある", en: "Yes, I have"},
  121300: {ja: "気を失ったことはない", en: "No, I have not"},
  121400: {ja: "二年以内に健康診断を受けたことはありますか", en: "Have you had a health checkup within the past two years?"},
  121500: {ja: "二年以内に健診を受けている", en: "Yes, within the past two years"},
  121600: {ja: "二年以内には健診を受けていない", en: "No, not within the past two years"},
  121700: {ja: "ある場合は、その内容を後で医師が確認します。", en: "If yes, the doctor will check the details later."},
  121800: {ja: "今までに大きな病気をしたことがありますか", en: "Have you ever had a serious illness?"},
  121900: {ja: "大きな病気をしたことがある", en: "Yes, I have had a serious illness"},
  122000: {ja: "人生で大きな病気をしたことはない", en: "No, I have never had a serious illness"},
  122100: {ja: "ある場合は、その内容を後で医師が確認します。", en: "If yes, the doctor will check the details later."},
  122200: {ja: "終了", en: "End"},

  130100: {ja: "問診内容確認", en: "Review the interview answers"},
  130200: {ja: "入力内容を確認してください", en: "Please check what you entered"},
  130300: {ja: "次へ", en: "Next"},
  130400: {ja: "やり直し", en: "Start over"},

  140100: {ja: "症状の経過", en: "When the fever started"},
  140200: {ja: "発熱は、いつ頃からありますか", en: "When did the fever start?"},
  140300: {ja: "数時間前から", en: "A few hours ago"},
  140400: {ja: "24時間以内", en: "Within the last 24 hours"},
  140500: {ja: "1日～数日前から", en: "One to several days ago"},
  140600: {ja: "1週間くらい前から", en: "About a week ago"},
  140700: {ja: "数週間前から", en: "Several weeks ago"},
  140800: {ja: "1か月くらい前から", en: "About a month ago"},
  140900: {ja: "数か月前から", en: "Several months ago"},
  141000: {ja: "半年以上前から", en: "More than six months ago"},
  141100: {ja: "わからない", en: "I don't know"},
  141200: {ja: "次へ", en: "Next"},

  150100: {ja: "めまいの経過", en: "When the dizziness started"},
  150200: {ja: "めまいは、いつ頃からありますか", en: "When did the dizziness start?"},
  150300: {ja: "数時間前から", en: "A few hours ago"},
  150400: {ja: "24時間以内", en: "Within the last 24 hours"},
  150500: {ja: "1日～数日前から", en: "One to several days ago"},
  150600: {ja: "1週間くらい前から", en: "About a week ago"},
  150700: {ja: "数週間前から", en: "Several weeks ago"},
  150800: {ja: "1か月くらい前から", en: "About a month ago"},
  150900: {ja: "数か月前から", en: "Several months ago"},
  151000: {ja: "半年以上前から", en: "More than six months ago"},
  151100: {ja: "わからない", en: "I don't know"},
  151200: {ja: "次へ", en: "Next"},

  160100: {ja: "最初のめまいの持続時間", en: "How long the first dizziness lasted"},
  160200: {ja: "最初にめまいを感じた時の話を聞かせてください", en: "Please tell us about the first time you felt dizzy."},
  160300: {ja: "その時のめまいはどのくらい続きましたか", en: "How long did that dizziness last?"},
  160400: {ja: "1分以内", en: "Less than 1 minute"},
  160500: {ja: "10分以内", en: "Less than 10 minutes"},
  160600: {ja: "1時間以内", en: "Less than 1 hour"},
  160700: {ja: "24時間以内", en: "Less than 24 hours"},
  160800: {ja: "1週間以内", en: "Less than 1 week"},
  160900: {ja: "1週間以上", en: "More than 1 week"},
  161000: {ja: "わからない", en: "I don't know"},
  161100: {ja: "次へ", en: "Next"}
};

// 行番号から現在の選択言語のテキストを返す関数
function 文字列取得(行番号){
  const 言語 = localStorage.getItem("選択言語") || "ja";
  if(辞書[行番号]){
    return 辞書[行番号][言語] || 辞書[行番号]["ja"];
  }
  return "？" + 行番号;
}
